---
- name: Test installed custom collection
  hosts: localhost
  gather_facts: false

  roles:
    - role: my_own_namespace.yandex_cloud_elk.create_file
      vars:
        my_own_module_path: /tmp/my_own_module_installed_collection_test.txt
        my_own_module_content: "Hello from installed custom collection"
